### ISSUE TITLE
Suggestion: Consider adding descriptions in your CSS code.

### ISSUE THREAD

**Issue by josephtkim** [eschmidtke/capstone#3]
It is a also a great idea to add descriptions within the CSS code, to make it easier to understand each section, and to improve the readability of the code. For instance, for the footer section:

```css
/* Footer */

footer {
  display:flex;
  align-items :center;
  justify-content: space-between;
  padding: 24px 24px 40px 24px;
  font-size: .8rem;
  border-top: 1px solid #ccc;
  color:#ccc;
}

footer ul li {
  display: inline;
  margin-left: 10px;
}
footer ul li a {
  color:#ccc;
}
```
